import {
  AlertTriangle,
  BarChart3,
  Book,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  ConciergeBell,
  DollarSign,
  DoorOpen,
  Factory,
  FileSignature,
  FileText,
  GraduationCap,
  HardHat,
  Headset,
  Hospital,
  Landmark,
  Layers,
  LayoutDashboard,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  MonitorPlay,
  PenLine,
  Recycle,
  Send,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Target,
  Thermometer,
  TrendingUp,
  Truck,
  UserCheck,
  UserCog,
  UserPlus,
  UserRound,
  Users,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";

// Icon fields on structural/content data are string keys (see types.ts for
// why) — this registry is the only place that resolves a key back to an
// actual Lucide component, and it must only be imported from client code.
export const ICONS: Record<string, LucideIcon> = {
  "alert-triangle": AlertTriangle,
  "bar-chart-3": BarChart3,
  book: Book,
  "book-open": BookOpen,
  box: Box,
  briefcase: Briefcase,
  "building-2": Building2,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "concierge-bell": ConciergeBell,
  "dollar-sign": DollarSign,
  "door-open": DoorOpen,
  factory: Factory,
  "file-signature": FileSignature,
  "file-text": FileText,
  "graduation-cap": GraduationCap,
  "hard-hat": HardHat,
  headset: Headset,
  hospital: Hospital,
  landmark: Landmark,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  "monitor-play": MonitorPlay,
  "pen-line": PenLine,
  recycle: Recycle,
  send: Send,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  smartphone: Smartphone,
  target: Target,
  thermometer: Thermometer,
  "trending-up": TrendingUp,
  truck: Truck,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "user-plus": UserPlus,
  "user-round": UserRound,
  users: Users,
  workflow: Workflow,
  wrench: Wrench,
};
